version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab_equipment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     DATABASE_URL: postgresql://postgres:password@db:5432/lab_equipment_db
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/app

volumes:
  postgres_data:
